// <auto-generated />
using System;
using Joint.Govern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joint.Govern.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Joint.Govern.Data.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Login = "admin",
                            PasswordHash = "F4E1B9EB0780D62BDB3B6193829F1721"
                        });
                });

            modelBuilder.Entity("Joint.Govern.Data.ModuleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<int>("ModuleInstanceId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ModuleInstanceId", "Key")
                        .IsUnique();

                    b.ToTable("ModuleConfigurations");
                });

            modelBuilder.Entity("Joint.Govern.Data.ModuleInstance", b =>
                {
                    b.Property<int>("ModuleInstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ConfigTime");

                    b.Property<bool>("Connected");

                    b.Property<string>("Endpoint");

                    b.Property<DateTime>("LastAccessTime");

                    b.Property<string>("Module")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ModuleInstanceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModuleInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
